# Controller key mappings
[mappings]
L_DPAD_UP = "XUSB_GAMEPAD_DPAD_UP"
L_DPAD_DOWN = "XUSB_GAMEPAD_DPAD_DOWN"
L_DPAD_LEFT = "XUSB_GAMEPAD_DPAD_LEFT"
L_DPAD_RIGHT = "XUSB_GAMEPAD_DPAD_RIGHT"
L_DPAD_SL = "XUSB_GAMEPAD_X"
L_DPAD_SR = "XUSB_GAMEPAD_A"