# Controller key mappings
[mappings]
# Left JoyCon
L_DPAD_UP = "DS4_BUTTON_DPAD_NORTH"
L_DPAD_DOWN = "DS4_BUTTON_DPAD_SOUTH"
L_DPAD_LEFT = "DS4_BUTTON_DPAD_WEST"
L_DPAD_RIGHT = "DS4_BUTTON_DPAD_EAST"
L_DPAD_SL = "XUSB_GAMEPAD_X"
L_DPAD_SR = "XUSB_GAMEPAD_A"
L_SHOULDER = "DS4_BUTTON_SHOULDER_LEFT"
L_TRIGGER = "DS4_BUTTON_TRIGGER_LEFT"
L_CAPTURE = "DS4_SPECIAL_BUTTON_TOUCHPAD"
L_MINUS = "DS4_BUTTON_SHARE"
L_STICK = "DS4_BUTTON_THUMB_LEFT"

# Right JoyCon
R_SHOULDER = "DS4_BUTTON_SHOULDER_RIGHT"
R_TRIGGER = "DS4_BUTTON_TRIGGER_RIGHT"
R_HOME = "DS4_SPECIAL_BUTTON_PS"
R_PLUS = "DS4_BUTTON_OPTIONS"
R_STICK = "DS4_BUTTON_THUMB_RIGHT"
R_BUT_A = "DS4_BUTTON_CIRCLE"
R_BUT_B = "DS4_BUTTON_CROSS"
R_BUT_X = "DS4_BUTTON_TRIANGLE"
R_BUT_Y = "DS4_BUTTON_SQUARE"
R_BUT_SL = "XUSB_GAMEPAD_B"
R_BUT_SR = "XUSB_GAMEPAD_Y"